version: '3'
services:
  uncoder-os:
    build:
      context: './uncoder-os/'
    container_name: uncoder-os
    restart: always
    environment:
      - HOST=0.0.0.0
    ports:
      - '4010:4010'
  translator:
    build:
      context: './uncoder-core/'
    container_name: uncoder-core
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    ports:
      - '8000:8000'